# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb8af256e8aaf218e240843e5b868b69d7dcd2e2c6b4be068fe91ba63ec57f5041b6af3dc2dbff464c7bf7d04e726c473f8c6808efafe68be57ce27980d21a69

test:
  secret_key_base: 4279bf5d85d08748cf7a6c6179a7f8449e9eb839523441adbf0f6ee4c86c61e3d9dd9ff2bff29e1a19d9c11d571a1d027774560d5b894cf397aeae1a5b160a6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
